"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { Prescription } from "@/types";
import { listFranchisePrescriptions } from "@/services/prescriptionService";
import { generatePrescriptionPdf } from "@/utils/pdf";
import { useAuth } from "@/hooks/useAuth";
import { formatISTDate } from "@/utils/date";
import { FileSignature, Download, Search, Eye } from "lucide-react";

export default function FranchisePrescriptionsPage() {
  const { user } = useAuth();
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");

  const franchiseId = user?.referenceId;

  useEffect(() => {
    async function load() {
      if (!franchiseId) return;
      try {
        const list = await listFranchisePrescriptions(franchiseId);
        setPrescriptions(list);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [franchiseId]);

  const handleDownload = (p: Prescription) => {
    const doc = generatePrescriptionPdf(p);
    doc.save(`CMGC_Prescription_${p.consultationId}.pdf`);
  };

  const filtered = prescriptions.filter(
    (p) =>
      p.patientNameSnapshot.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.prescriptionId.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.consultationId.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-cmgc-primary border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">
          Prescriptions & Medical Records
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Download certified CMGC electronic prescriptions generated by consulting doctors.
        </p>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs">
        <div className="relative max-w-md">
          <Search className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search by patient name, prescription ID, consultation ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full rounded-lg border border-slate-300 pl-9 pr-3 py-2 text-xs focus:border-cmgc-primary focus:ring-1 focus:ring-cmgc-primary focus:outline-none"
          />
        </div>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-600">
            <thead className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold uppercase tracking-wider text-slate-500">
              <tr>
                <th className="px-4 py-3">Prescription ID</th>
                <th className="px-4 py-3">Consultation</th>
                <th className="px-4 py-3">Patient</th>
                <th className="px-4 py-3">Doctor</th>
                <th className="px-4 py-3">Diagnosis</th>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3 text-right">PDF Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-12 text-center text-slate-400">
                    No prescriptions found. Prescriptions are generated after consultations are completed.
                  </td>
                </tr>
              ) : (
                filtered.map((p) => (
                  <tr key={p.prescriptionId} className="hover:bg-slate-50 transition">
                    <td className="px-4 py-3.5 font-mono font-medium text-slate-900">
                      {p.prescriptionId}
                    </td>
                    <td className="px-4 py-3.5 font-mono text-cmgc-primary font-semibold">
                      {p.consultationId}
                    </td>
                    <td className="px-4 py-3.5 font-bold text-slate-900">
                      {p.patientNameSnapshot}
                    </td>
                    <td className="px-4 py-3.5 text-slate-800">{p.doctorNameSnapshot}</td>
                    <td className="px-4 py-3.5 font-medium text-slate-700 max-w-xs truncate">
                      {p.diagnosis}
                    </td>
                    <td className="px-4 py-3.5 text-slate-500">{formatISTDate(p.createdAt)}</td>
                    <td className="px-4 py-3.5 text-right">
                      <button
                        onClick={() => handleDownload(p)}
                        className="inline-flex items-center gap-1.5 rounded-lg bg-cmgc-primary px-3 py-1.5 text-xs font-bold text-white hover:bg-cmgc-navy transition shadow-2xs"
                      >
                        <Download className="h-3.5 w-3.5" /> PDF
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
